# Generated by Django 5.0.6 on 2024-09-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='symmetric_pdf',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
