# Generated by Django 5.0.6 on 2024-09-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uploadedimage_symmetric_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='phi_pdf',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
