# Generated by Django 5.0.6 on 2024-12-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_uploadedimage_processed_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='bulge_image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='shrink_image',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
